### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by BrandonMurnane** [yatki/read-env#2]
Hi im using this package in a project thats also using webpack and in the backend works great but front end doesnt work

**Comment by yatki** [comment]
Hey @BrandonMurnane, 

Thanks for the raising the issue. 

Just to give you a quick feedback, I didn't consider supporting browser usage when I wrote this library, because I didn't need that back then. However since there is a need for somebody else now, I'll add browser support within next few days.

**Comment by BrandonMurnane** [comment]
hi i was wondering if any update on this yet ?

**Comment by yatki** [comment]
Hi @BrandonMurnane, actually i implemented the browserified version here: https://github.com/yatki/read-env/tree/2-browserify but I couldn't publish to npm yet. Planning to do it this weekend. So sorry for delay.

**Comment by BrandonMurnane** [comment]
great thanks alot for the work and update @yatki

**Comment by yatki** [comment]
@BrandonMurnane you should be able to use version 1.3.0 in the browser now. Please let me know if you experience further issues.
